logging:
  level:
    root: debug

server:
  port: 8080

base:
  bio: Hello!
  img:
    url: image.png

auth:
  header : Authorization
  type : BEARER

spring:
  jackson:
    deserialization:
      unwrap-root-value: true
    serialization:
      wrap-root-value: true